# Generated by Django 2.2.1 on 2019-05-27 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('MO', 'Monthly'), ('AH', 'Add Hoc'), ('WY', 'Weekly'), ('FN', 'Fortnightly')], default='FN', max_length=2, verbose_name='Payment Frequency')),
                ('take_home_pay', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Take Home Pay')),
                ('date_active_from', models.DateField(verbose_name='Date Active From')),
                ('owner', models.ForeignKey(on_delete=None, related_name='payconfiguration_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Acc Number')),
                ('name', models.CharField(max_length=50, verbose_name='Acc Name')),
                ('display_name', models.CharField(max_length=50, verbose_name='Display Name')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
                ('balance_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('owner', models.ForeignKey(on_delete=None, related_name='budget_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
