# Generated by Django 2.2.1 on 2019-06-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20190604_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('AP', 'At Pay'), ('AH', 'Add Hoc'), ('QY', 'Quarterly'), ('MO', 'Monthly')], default='AP', max_length=2, verbose_name='Expense Frequency'),
        ),
        migrations.AlterField(
            model_name='payconfiguration',
            name='frequency',
            field=models.CharField(choices=[('MO', 'Monthly'), ('AH', 'Add Hoc'), ('WY', 'Weekly'), ('FN', 'Fortnightly')], default='FN', max_length=2, verbose_name='Payment Frequency'),
        ),
    ]
